receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:

exporters:
  logging:
    loglevel: info
  prometheus:
    endpoint: "0.0.0.0:8889"
  loki:
    endpoint: "http://localhost:3100/loki/api/v1/push"
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus,logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki,logging]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]