global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'pedido-service'
    metrics_path: '/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['pedido-service:8081']

  - job_name: 'postgres'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['postgres-exporter:9187']